import './styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}

      <script defer src="https://unpkg.com/mathlive"></script>
      </body>
    </html>
  )
}
